/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cursoemvideo.soma;

/**
 *
 * @author joao
 */
public class calcular extends javax.swing.JFrame {

    /**
     * Creates new form calcular
     */
    public calcular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRes4 = new javax.swing.JLabel();
        lblRes5 = new javax.swing.JLabel();
        lblRes6 = new javax.swing.JLabel();
        btIgual7 = new javax.swing.JButton();
        txt9 = new javax.swing.JTextField();
        btIgual6 = new javax.swing.JButton();
        lblMais7 = new javax.swing.JLabel();
        lblMais5 = new javax.swing.JLabel();
        txt13 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        lblRes7 = new javax.swing.JLabel();
        lblMais6 = new javax.swing.JLabel();
        txt14 = new javax.swing.JTextField();
        lblMais4 = new javax.swing.JLabel();
        txt16 = new javax.swing.JTextField();
        btIgual4 = new javax.swing.JButton();
        txt10 = new javax.swing.JTextField();
        btIgual5 = new javax.swing.JButton();
        txt15 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        lblMais = new javax.swing.JLabel();
        lblRes = new javax.swing.JLabel();
        btIgual = new javax.swing.JButton();
        txt2 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        lblcalc = new javax.swing.JLabel();
        lblMais1 = new javax.swing.JLabel();
        txt4 = new javax.swing.JTextField();
        lblRes1 = new javax.swing.JLabel();
        txt3 = new javax.swing.JTextField();
        btIgual1 = new javax.swing.JButton();
        txt8 = new javax.swing.JTextField();
        lblRes2 = new javax.swing.JLabel();
        txt7 = new javax.swing.JTextField();
        btIgual2 = new javax.swing.JButton();
        lblMais2 = new javax.swing.JLabel();
        txt6 = new javax.swing.JTextField();
        lblRes3 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        btIgual3 = new javax.swing.JButton();
        lblMais3 = new javax.swing.JLabel();
        txt20 = new javax.swing.JTextField();
        txt19 = new javax.swing.JTextField();
        lblMais10 = new javax.swing.JLabel();
        lblRes10 = new javax.swing.JLabel();
        btIgual11 = new javax.swing.JButton();
        lblMais11 = new javax.swing.JLabel();
        lblRes11 = new javax.swing.JLabel();
        btIgual12 = new javax.swing.JButton();
        txt21 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        lblMais13 = new javax.swing.JLabel();
        lblMais14 = new javax.swing.JLabel();
        lblMais15 = new javax.swing.JLabel();
        lblRes13 = new javax.swing.JLabel();
        btIgual14 = new javax.swing.JButton();
        txt25 = new javax.swing.JTextField();
        txt26 = new javax.swing.JTextField();

        lblRes4.setText("0");

        lblRes5.setText("0");

        lblRes6.setText("0");

        btIgual7.setText("=");
        btIgual7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual7ActionPerformed(evt);
            }
        });

        btIgual6.setText("=");
        btIgual6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual6ActionPerformed(evt);
            }
        });

        lblMais7.setText("*");

        lblMais5.setText("-");

        lblRes7.setText("0");

        lblMais6.setText("+");

        lblMais4.setText("/");

        btIgual4.setText("=");
        btIgual4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual4ActionPerformed(evt);
            }
        });

        btIgual5.setText("=");
        btIgual5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMais.setText("+");

        lblRes.setText("0");

        btIgual.setText("=");
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });

        lblcalc.setText("Calculadora by professor Joao Moreira");

        lblMais1.setText("-");

        lblRes1.setText("0");

        btIgual1.setText("=");
        btIgual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual1ActionPerformed(evt);
            }
        });

        lblRes2.setText("0");

        btIgual2.setText("=");
        btIgual2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual2ActionPerformed(evt);
            }
        });

        lblMais2.setText("*");

        lblRes3.setText("0");

        btIgual3.setText("=");
        btIgual3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual3ActionPerformed(evt);
            }
        });

        lblMais3.setText("/");

        lblMais10.setText("resto");

        lblRes10.setText("0");

        btIgual11.setText("=");
        btIgual11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual11ActionPerformed(evt);
            }
        });

        lblMais11.setText("  -");

        lblRes11.setText("0");

        btIgual12.setText("=");
        btIgual12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual12ActionPerformed(evt);
            }
        });

        lblMais13.setText("%");

        lblMais14.setText("%");

        lblMais15.setText("  +");

        lblRes13.setText("0");

        btIgual14.setText("=");
        btIgual14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgual14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblcalc, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt3)
                            .addComponent(txt1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMais, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMais1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIgual1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRes, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(lblRes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt7)
                            .addComponent(txt5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMais2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMais3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIgual2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btIgual3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblRes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(lblMais10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btIgual11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRes10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lblMais11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblMais13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btIgual12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRes11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lblMais15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lblMais14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btIgual14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRes13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblcalc)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMais)
                    .addComponent(lblRes)
                    .addComponent(btIgual)
                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMais1)
                    .addComponent(lblRes1)
                    .addComponent(btIgual1)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMais2)
                    .addComponent(lblRes3)
                    .addComponent(btIgual3)
                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMais3)
                    .addComponent(lblRes2)
                    .addComponent(btIgual2)
                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMais10)
                    .addComponent(lblRes10)
                    .addComponent(btIgual11)
                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMais11)
                    .addComponent(lblRes11)
                    .addComponent(btIgual12)
                    .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMais13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblMais15)
                    .addComponent(lblRes13)
                    .addComponent(btIgual14)
                    .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMais14))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btIgual, lblMais, lblRes});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualActionPerformed
        // TODO add your handling code here:
        int n1 = Integer.parseInt(txt1.getText());
        int n2 = Integer.parseInt(txt2.getText());
        int s = n1 + n2;
        lblRes.setText(Integer.toString(s));
    }//GEN-LAST:event_btIgualActionPerformed

    private void btIgual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual1ActionPerformed
        // TODO add your handling code here:
        int n3 = Integer.parseInt(txt3.getText());
        int n4 = Integer.parseInt(txt4.getText());
        int s = n3 - n4;
        lblRes1.setText(Integer.toString(s));
    }//GEN-LAST:event_btIgual1ActionPerformed

    private void btIgual2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual2ActionPerformed
        // TODO add your handling code here:
        int n7 = Integer.parseInt(txt7.getText());
        int n8 = Integer.parseInt(txt8.getText());
        int s = n7 / n8;
        lblRes2.setText(Integer.toString(s));
        
    }//GEN-LAST:event_btIgual2ActionPerformed

    private void btIgual3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual3ActionPerformed
        // TODO add your handling code here:
        int n5 = Integer.parseInt(txt5.getText());
        int n6 = Integer.parseInt(txt6.getText());
        int s = n5 * n6;
        lblRes3.setText(Integer.toString(s));
        
    }//GEN-LAST:event_btIgual3ActionPerformed

    private void btIgual4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIgual4ActionPerformed

    private void btIgual5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIgual5ActionPerformed

    private void btIgual6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIgual6ActionPerformed

    private void btIgual7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btIgual7ActionPerformed

    private void btIgual11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual11ActionPerformed
        // TODO add your handling code here:
        int n19 = Integer.parseInt(txt19.getText());
        int n20 = Integer.parseInt(txt20.getText());
        int s = n19 % n20;
        lblRes10.setText(Integer.toString(s));
    }//GEN-LAST:event_btIgual11ActionPerformed

    private void btIgual12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual12ActionPerformed
        // TODO add your handling code here:
        int n22 = Integer.parseInt(txt22.getText());
        int n21 = Integer.parseInt(txt21.getText());
        int s = ((n22 * n21) / 100);
        int s1 = n22 - s;
        lblRes11.setText(Integer.toString(s1));
    }//GEN-LAST:event_btIgual12ActionPerformed

    private void btIgual14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgual14ActionPerformed
        // TODO add your handling code here:
        int n26 = Integer.parseInt(txt26.getText());
        int n25 = Integer.parseInt(txt25.getText());
        int s = ((n26 * n25) / 100);
        int s1 = n26 + s;
        lblRes13.setText(Integer.toString(s1));
    }//GEN-LAST:event_btIgual14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btIgual1;
    private javax.swing.JButton btIgual11;
    private javax.swing.JButton btIgual12;
    private javax.swing.JButton btIgual14;
    private javax.swing.JButton btIgual2;
    private javax.swing.JButton btIgual3;
    private javax.swing.JButton btIgual4;
    private javax.swing.JButton btIgual5;
    private javax.swing.JButton btIgual6;
    private javax.swing.JButton btIgual7;
    private javax.swing.JLabel lblMais;
    private javax.swing.JLabel lblMais1;
    private javax.swing.JLabel lblMais10;
    private javax.swing.JLabel lblMais11;
    private javax.swing.JLabel lblMais13;
    private javax.swing.JLabel lblMais14;
    private javax.swing.JLabel lblMais15;
    private javax.swing.JLabel lblMais2;
    private javax.swing.JLabel lblMais3;
    private javax.swing.JLabel lblMais4;
    private javax.swing.JLabel lblMais5;
    private javax.swing.JLabel lblMais6;
    private javax.swing.JLabel lblMais7;
    private javax.swing.JLabel lblRes;
    private javax.swing.JLabel lblRes1;
    private javax.swing.JLabel lblRes10;
    private javax.swing.JLabel lblRes11;
    private javax.swing.JLabel lblRes13;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblRes3;
    private javax.swing.JLabel lblRes4;
    private javax.swing.JLabel lblRes5;
    private javax.swing.JLabel lblRes6;
    private javax.swing.JLabel lblRes7;
    private javax.swing.JLabel lblcalc;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt19;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables
}
