/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

import java.awt.Font;
import static javafx.scene.text.Font.font;
import static javafx.scene.text.Font.font;

/**
 *
 * @author joao
 */
public class genio extends javax.swing.JFrame {

    /**
     * Creates new form genio
     */
    public genio() { //construtor
        initComponents();
        lblFrase.setText("<html>Vou pensar em um valor entre <strong>1 e 5,</strong> tente adivinhar</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase = new javax.swing.JLabel();
        btnPal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEntrada = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFrase.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(0, 0, 0));
        lblFrase.setText("Frase");
        lblFrase.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblFraseAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, 110));

        btnPal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnPal.setText("Palpite");
        btnPal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalActionPerformed(evt);
            }
        });
        getContentPane().add(btnPal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 170, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -20, 420, 290));

        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        txtEntrada.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 188, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalActionPerformed
        // TODO add your handling code here:
        double n = 1 + Math.random() * (6 -1);
        int valor = (int)n;
        int num = Integer.parseInt(txtEntrada.getValue().toString());
        String f1 = "<html>Parabens Acertou</html>";
        String f2 = "<html>Errou, eu pensei no valor: <strong>" + valor + "</strong></html>";
        String res = (valor == num)?f1:f2;
        lblFrase.setFont(new Font("Arial Black",Font.PLAIN,14));
        lblFrase.setText(res);
    }//GEN-LAST:event_btnPalActionPerformed

    private void lblFraseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblFraseAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFraseAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(genio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new genio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JSpinner txtEntrada;
    // End of variables declaration//GEN-END:variables
}
